name: macos
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
      - name: Build
        run: |
          make webviewer-build-macos
      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: binaryname-macos-arm64
          path: ./build/binaryname